import type { LanguageRegistration } from "shiki";

// Arma 3 SQF scripting commands — sourced from
// https://community.bistudio.com/wiki/Category:Arma_3:_Scripting_Commands
// Sorted longest-first so oniguruma alternation matches greedily.
const SQF_COMMANDS = [
  "getCalculatePlayerVisibilityByFriendly", "leaderboardRequestRowsGlobalAroundUser", "leaderboardsRequestUploadScoreKeepBest", "addWeaponWithAttachmentsCargoGlobal", "calculatePlayerVisibilityByFriendly", "removeAllUserActionEventHandlers",
  "setDynamicSimulationDistanceCoef", "isMissionProfileNamespaceLoaded", "lnbSetPictureColorSelectedRight", "dynamicSimulationSystemEnabled", "lbSetPictureRightColorDisabled", "lbSetPictureRightColorSelected",
  "leaderboardsRequestUploadScore", "setVehicleReceiveRemoteTargets", "tvSetPictureRightColorDisabled", "tvSetPictureRightColorSelected", "addPublicVariableEventHandler", "addWeaponWithAttachmentsCargo",
  "directionStabilizationEnabled", "displayRemoveAllEventHandlers", "dynamicSimulationDistanceCoef", "enableDynamicSimulationSystem", "getCustomSoundControllerCount", "leaderboardRequestRowsFriends",
  "removeAllMissionEventHandlers", "removeAllSecondaryWeaponItems", "setVehicleReportRemoteTargets", "allowCuratorLogicIgnoreAreas", "diag_allMissionEventHandlers", "diag_getTerrainSegmentOffset",
  "enableDirectionStabilization", "getArtilleryComputerSettings", "isAISteeringComponentEnabled", "leaderboardRequestRowsGlobal", "removeAllCuratorEditingAreas", "removeCuratorEditableObjects",
  "removeUserActionEventHandler", "setAngularVelocityModelSpace", "setDynamicSimulationDistance", "cancelSimpleTaskDestination", "canTriggerDynamicSimulation", "config_greater_greater_name",
  "currentMagazineDetailTurret", "diag_dynamicSimulationStart", "getAllEnv3DSoundControllers", "getCompatiblePylonMagazines", "removeAllCuratorCameraAreas", "removeAllItemsWithMagazines",
  "removeAllMusicEventHandlers", "removeAllPrimaryWeaponItems", "removeWeaponAttachmentCargo", "saveMissionProfileNamespace", "set3DENAttachedCursorEntity", "setCuratorCameraAreaCeiling",
  "setVehicleReportOwnPosition", "setWaypointCompletionRadius", "useAIOperMapObstructionTest", "vehicleReceiveRemoteTargets", "buldozer_isEnabledRoadDiag", "ctrlRemoveAllEventHandlers",
  "ctrlSetFontHeightSecondary", "isUsingAISteeringComponent", "lnbSetPictureColorSelected", "loadCuratorSelectionPreset", "nearestLocationWithDubbing", "removeAll3DENEventHandlers",
  "removeFromRemainsCollector", "setSimpleTaskAlwaysVisible", "vehicleReportRemoteTargets", "addCuratorEditableObjects", "addUserActionEventHandler", "angularVelocityModelSpace",
  "clearAllItemsFromBackpack", "ctrlSetTextColorSecondary", "diag_dynamicSimulationEnd", "displayRemoveEventHandler", "dynamicSimulationDistance", "edit3DENMissionAttributes",
  "getAllEnvSoundControllers", "infoPanelComponentEnabled", "isInstructorFigureEnabled", "isStreamFriendlyUIEnabled", "lbSetPictureColorDisabled", "lbSetPictureColorSelected",
  "onHCGroupSelectionChanged", "preprocessFileLineNumbers", "removeMissionEventHandler", "removeSecondaryWeaponItem", "setCuratorEditingAreaType", "setCuratorSelectionPreset",
  "setVelocityTransformation", "setVisibleIfTreeCollapsed", "setWaypointForceBehaviour", "setWaypointLoiterAltitude", "tvSetPictureColorDisabled", "tvSetPictureColorSelected",
  "clearBackpackCargoGlobal", "clearMagazineCargoGlobal", "ctrlSetTooltipColorShade", "curatorCameraAreaCeiling", "curatorRegisteredObjects", "disableUAVConnectability",
  "dynamicSimulationEnabled", "enableInfoPanelComponent", "forceHitPointsDamageSync", "get3DENMissionAttributes", "getCustomSoundController", "getPilotCameraOpticsMode",
  "getRemoteSensorsDisabled", "getSoundControllerResult", "removeAllMPEventHandlers", "removeCuratorEditingArea", "set3DENMissionAttributes", "setCustomSoundController",
  "setLightFlareMaxDistance", "setPilotCameraOpticsMode", "setSimpleTaskDescription", "setSimpleTaskDestination", "setUnitRecoilCoefficient", "setWaypointHousePosition",
  "synchronizeObjectsRemove", "triggerDynamicSimulation", "vectorModelToWorldVisual", "vectorWorldToModelVisual", "vehicleReportOwnPosition", "waypointCompletionRadius",
  "weaponDisassemblyEnabled", "activeTitleEffectParams", "buldozer_enableRoadDiag", "camConstuctionSetParams", "createMPCampaignDisplay", "ctrlAnimationPhaseModel",
  "ctrlParentControlsGroup", "ctrlSetAutoScrollRewind", "ctrlSetTooltipColorText", "diag_captureFrameToFile", "diag_dumpCalltraceToLog", "diag_dumpScriptAssembly",
  "diag_recordTurretLimits", "enableDynamicSimulation", "enableSatNormalOnDetail", "enableUAVConnectability", "enableWeaponDisassembly", "get3DENMissionAttribute",
  "getAssignedCuratorLogic", "getDLCAssetsUsageByName", "getEnv3DSoundController", "getFieldManualStartPage", "getMissionLayerEntities", "getPhysicsCollisionFlag",
  "getPilotCameraDirection", "inGameUISetEventHandler", "isAllowedCrewInImmobile", "isAutoStartUpEnabledRTD", "isGroupDeletedWhenEmpty", "isSensorTargetConfirmed",
  "lnbSetPictureColorRight", "magazinesDetailBackpack", "missionProfileNamespace", "modelToWorldVisualWorld", "radioChannelSetCallSign", "removeAllBinocularItems",
  "removeCuratorCameraArea", "removeMusicEventHandler", "removePrimaryWeaponItem", "secondaryWeaponMagazine", "selectionVectorDirAndUp", "serverCommandExecutable",
  "set3DENMissionAttribute", "setGroupIconsSelectable", "setObjectMaterialGlobal", "setPhysicsCollisionFlag", "setPilotCameraDirection", "setSimpleTaskCustomData",
  "setWaypointLoiterRadius", "slingLoadAssistantShown", "waypointAttachedVehicle", "addBackpackCargoGlobal", "addMagazineCargoGlobal", "addMissionEventHandler",
  "addSecondaryWeaponItem", "buldozer_reloadOperMap", "clearWeaponCargoGlobal", "commandSuppressiveFire", "createHashMapFromArray", "createSoundSourceLocal",
  "ctrlRemoveEventHandler", "ctrlSetAutoScrollDelay", "ctrlSetAutoScrollSpeed", "ctrlSetBackgroundColor", "ctrlSetForegroundColor", "ctrlSetTooltipColorBox",
  "ctrlSetTooltipMaxWidth", "curatorEditableObjects", "curatorEditingAreaType", "curatorSelectionPreset", "customWaypointPosition", "diag_activeMissionFSMs",
  "disableDebriefingStats", "displayAddEventHandler", "displaySetEventHandler", "enableSimulationGlobal", "estimatedEndServerTime", "findEmptyPositionReady",
  "getAllSoundControllers", "getAssignedCuratorUnit", "getCameraViewDirection", "getCorpseWeaponholders", "getFuelConsumptionCoef", "getPilotCameraPosition",
  "getPilotCameraRotation", "getSteamFriendsServers", "getWaterFillPercentage", "getWingsOrientationRTD", "isVehicleSensorEnabled", "lbSetPictureRightColor",
  "lineIntersectsSurfaces", "magazinesDetailUniform", "remove3DENEventHandler", "removeAllAssignedItems", "removeAllCuratorAddons", "removeAllEventHandlers",
  "removeItemFromBackpack", "resetSubgroupDirection", "screenToWorldDirection", "serverCommandAvailable", "setActualCollectiveRTD", "setCuratorWaypointCost",
  "setDiarySubjectPicture", "setFuelConsumptionCoef", "setHorizonParallaxCoef", "setMarkerPolylineLocal", "setObjectTextureGlobal", "setPilotCameraRotation",
  "setWaterFillPercentage", "setWaypointDescription", "setWeaponReloadingTime", "shownArtilleryComputer", "triggerAttachedVehicle", "tvSetPictureRightColor",
  "useAISteeringComponent", "vectorLinearConversion", "waypointAttachedObject", "waypointForceBehaviour", "waypointLoiterAltitude", "waypointTimeoutCurrent",
  "weaponAccessoriesCargo", "addCuratorEditingArea", "addToRemainsCollector", "allActiveTitleEffects", "buldozer_loadNewRoads", "cameraEffectEnableHUD",
  "collisionDisabledWith", "configSourceAddonList", "create3DENComposition", "ctrlSetPixelPrecision", "ctrlSetStructuredText", "ctrlSetURLOverlayMode",
  "currentMagazineDetail", "currentMagazineTurret", "diag_activeSQFScripts", "diag_activeSQSScripts", "diag_captureSlowFrame", "diag_dumpTerrainSynth",
  "diag_exportTerrainSVG", "diag_getTerrainHeight", "diag_remainsCollector", "diag_setTerrainHeight", "editorSetEventHandler", "enableDebriefingStats",
  "enableEngineArtillery", "getAllHitPointsDamage", "getAudioOptionVolumes", "getCursorObjectParams", "getEngineTargetRPMRTD", "getEnvSoundController",
  "getMissionConfigValue", "getObjectViewDistance", "getRespawnVehicleInfo", "hierarchyObjectsCount", "isAimPrecisionEnabled", "isFilePatchingEnabled",
  "isMarkedForCollection", "isSteamOverlayEnabled", "isStressDamageEnabled", "lbSetSelectColorRight", "lnbGetColumnsPosition", "markAsFinishedOnSteam",
  "nearestTerrainObjects", "positionCameraToWorld", "primaryWeaponMagazine", "progressLoadingScreen", "removeAllHandgunItems", "removeItemFromUniform",
  "removeMagazinesTurret", "selectedEditorObjects", "setCompassDeclination", "setCompassOscillation", "setDetailMapBlendPars", "setEffectiveCommander",
  "setFlagAnimationPhase", "setMagazineTurretAmmo", "setMarkerDrawPriority", "setObjectViewDistance", "setSimulWeatherLayers", "setUnitFreefallHeight",
  "setVelocityModelSpace", "setWaypointCombatMode", "setWaypointLoiterType", "setWaypointStatements", "synchronizedWaypoints", "synchronizeObjectsAdd",
  "terrainIntersectAtASL", "triggerTimeoutCurrent", "unitAimPositionVisual", "unitRecoilCoefficient", "waypointAttachVehicle", "waypointHousePosition",
  "actionKeysNamesArray", "addCuratorCameraArea", "addForceGeneratorRTD", "addMagazineAmmoCargo", "addMusicEventHandler", "addPrimaryWeaponItem",
  "addWeaponCargoGlobal", "allEnv3DSoundSources", "animationSourcePhase", "canAddItemToBackpack", "clearItemCargoGlobal", "commandArtilleryFire",
  "connectTerminalToUAV", "conversationDisabled", "createMissionDisplay", "ctrlAutoScrollRewind", "ctrlMapScreenToWorld", "ctrlMapWorldToScreen",
  "ctrlSetDisabledColor", "ctrlSetFontSecondary", "ctrlSetModelDirAndUp", "ctrlSetMousePosition", "ctrlSetTextSecondary", "ctrlSetTextSelection",
  "current3DENOperation", "deleteGroupWhenEmpty", "diag_codePerformance", "diag_mergeConfigFile", "difficultyEnabledRTD", "disableCollisionWith",
  "disableMapIndicators", "disableRemoteSensors", "disableSerialization", "enableAutoStartUpRTD", "forceCadetDifficulty", "get3DENLayerEntities",
  "getBleedingRemaining", "getClientStateNumber", "getEditorObjectScope", "getForcedFlagTexture", "getPilotCameraTarget", "getTotalDLCUsageTime",
  "isInRemainsCollector", "kbAddDatabaseTargets", "onBriefingTeamSwitch", "onCommandModeChanged", "onGroupIconOverEnter", "onGroupIconOverLeave",
  "onPlayerDisconnected", "openCuratorInterface", "publicVariableClient", "publicVariableServer", "radioChannelSetLabel", "remove3DENConnection",
  "removeBackpackGlobal", "removeMagazineGlobal", "removeMagazineTurret", "removeMPEventHandler", "removeSwitchableUnit", "saveProfileNamespace",
  "secondaryWeaponItems", "selectRandomWeighted", "set3DENModelsVisible", "setBleedingRemaining", "setCamShakeDefParams", "setCustomMissionData",
  "setEditorObjectScope", "setForceGeneratorRTD", "setGroupIconsVisible", "setHUDMovementLevels", "setMarkerShadowLocal", "setMusicEventHandler",
  "setPilotCameraTarget", "setPlayerRespawnTime", "setTriggerActivation", "setTriggerStatements", "setWaypointBehaviour", "setWaypointFormation",
  "setWingForceScaleRTD", "synchronizedTriggers", "triggerAttachVehicle", "useAudioTimeForMoves", "waypointAttachObject", "waypointLoiterRadius",
  "add3DENEventHandler", "allowCrewInImmobile", "allowFileOperations", "assignedVehicleRole", "bezierInterpolation", "canAddItemToUniform",
  "compatibleMagazines", "configSourceModList", "confirmSensorTarget", "createHashMapObject", "ctrlAddEventHandler", "ctrlAutoScrollDelay",
  "ctrlAutoScrollSpeed", "ctrlBackgroundColor", "ctrlForegroundColor", "ctrlModelVectorSide", "ctrlSetEventHandler", "ctrlSetFontHeightH1",
  "ctrlSetFontHeightH2", "ctrlSetFontHeightH3", "ctrlSetFontHeightH4", "ctrlSetFontHeightH5", "ctrlSetFontHeightH6", "ctrlSetScrollValues",
  "ctSetHeaderTemplate", "curatorWaypointCost", "currentWeaponTurret", "diag_getTerrainGrid", "disableConversation", "disableNVGEquipment",
  "enableCollisionWith", "enableVehicleSensor", "expectedDestination", "fillWeaponsFromPool", "get3DENIconsVisible", "get3DENLinesVisible",
  "getAnimAimPrecision", "getConnectedUAVUnit", "getContainerMaxLoad", "getEventHandlerInfo", "getTerrainHeightASL", "getTurretOpticsMode",
  "getUnitFreefallInfo", "getWingsPositionRTD", "groupIconSelectable", "infoPanelComponents", "isActionMenuVisible", "isRemoteControlling",
  "isRemoteExecutedJIP", "logNetworkTerminate", "magazinesAllTurrets", "magazinesDetailVest", "playableSlotsNumber", "playScriptedMission",
  "progressSetPosition", "remoteExecutedJIPID", "remoteExecutedOwner", "removeAllContainers", "removeAllOwnedMines", "removeBinocularItem",
  "removeCuratorAddons", "restartEditorCamera", "ropeAttachedObjects", "save3DENPreferences", "set3DENIconsVisible", "set3DENLinesVisible",
  "setAirplaneThrottle", "setConvoySeparation", "setLightAttenuation", "setLightVolumeShape", "setMarkerAlphaLocal", "setMarkerBrushLocal",
  "setMarkerColorLocal", "setMarkerShapeLocal", "setMissileTargetPos", "setSimpleTaskTarget", "setTaskMarkerOffset", "setTurretOpticsMode",
  "setWaypointPosition", "shownCuratorCompass", "showNewEditorObject", "simulCloudOcclusion", "synchronizedObjects", "synchronizeWaypoint",
  "terrainIntersectASL", "triggerAttachObject", "vehicleCargoEnabled", "waypointDescription", "waypointsEnabledUAV", "weaponReloadingTime",
  "addCuratorSelected", "addItemCargoGlobal", "airDensityCurveRTD", "ambientTemperature", "assignAsCargoIndex", "campaignConfigFile",
  "camPrepareFovRange", "clear3DENAttribute", "clear3DENInventory", "clearBackpackCargo", "clearMagazineCargo", "collapseObjectTree",
  "collect3DENHistory", "createDiarySubject", "createGuardedPoint", "createSimpleObject", "createVehicleLocal", "ctrlMapSetPosition",
  "ctrlSetActiveColor", "ctrlURLOverlayMode", "curatorEditingArea", "delete3DENEntities", "deleteEditorObject", "diag_activeScripts",
  "diag_SQFCDebugDump", "diarySubjectExists", "disableTIEquipment", "distributionRegion", "effectiveCommander", "enableAimPrecision",
  "enableAudioFeature", "enablePersonTurret", "enableStressDamage", "enableUAVWaypoints", "enableVehicleCargo", "environmentEnabled",
  "evalObjectArgument", "exportLandscapeXYZ", "flagAnimationPhase", "forceAtPositionRTD", "forceWeatherChange", "forEachMemberAgent",
  "formationDirection", "get3DENActionState", "get3DENConnections", "getElevationOffset", "getGroupIconParams", "getMusicPlayedTime",
  "getObjectMaterials", "getOxygenRemaining", "getPiPViewDistance", "getPlayerVoNVolume", "getSoundController", "getSubtitleOptions",
  "groupSelectedUnits", "inAreaArrayIndexes", "incapacitatedState", "inRangeOfArtillery", "insertEditorObject", "isCollisionLightOn",
  "itemsWithMagazines", "leaderboardGetRows", "libraryDisclaimers", "lineIntersectsObjs", "lineIntersectsWith", "listVehicleSensors",
  "lnbSetPictureColor", "lnbSetPictureRight", "magazinesAmmoCargo", "magazineTurretAmmo", "markerDrawPriority", "modelToWorldVisual",
  "numberOfEnginesRTD", "periscopeElevation", "pixelGridNoUIScale", "ppEffectForceInNVG", "primaryWeaponItems", "radioChannelCreate",
  "radioChannelRemove", "removeDiarySubject", "removeEventHandler", "removeItemFromVest", "removeWeaponGlobal", "removeWeaponTurret",
  "reportRemoteTarget", "selectDiarySubject", "selectEditorObject", "selectWeaponTurret", "setAngularVelocity", "setBehaviourStrong",
  "setCombatBehaviour", "setCuratorSelected", "setCurrentWaypoint", "setCustomWeightRTD", "setDiaryRecordText", "setEffectCondition",
  "setGroupIconParams", "setLightBrightness", "setLocalWindParams", "setMarkerSizeLocal", "setMarkerTextLocal", "setMarkerTypeLocal",
  "setObjectArguments", "setOxygenRemaining", "setPiPViewDistance", "setPlayerVoNVolume", "setTrafficDistance", "setTriggerInterval",
  "setVehiclePosition", "setWaypointTimeout", "setWaypointVisible", "showCommandingMenu", "showCuratorCompass", "startLoadingScreen",
  "synchronizeTrigger", "vectorCrossProduct", "vectorMagnitudeSqr", "vectorModelToWorld", "vectorWorldToModel", "velocityModelSpace",
  "visiblePositionASL", "waypointCombatMode", "waypointLoiterType", "waypointStatements", "worldToModelVisual", "add3DENConnection",
  "addBackpackGlobal", "addItemToBackpack", "addMagazineGlobal", "addMagazineTurret", "addMPEventHandler", "addSwitchableUnit",
  "allMissionObjects", "assignAsCommander", "assignedCommander", "backpackContainer", "backpackMagazines", "binocularMagazine",
  "camCommitPrepared", "canUnloadInCombat", "clearMagazinePool", "controlsGroupCtrl", "copyFromClipboard", "createDiaryRecord",
  "createMarkerLocal", "createSoundSource", "createVehicleCrew", "ctrlMapAnimCommit", "ctrlModelDirAndUp", "ctrlMousePosition",
  "ctrlSetFontHeight", "ctrlSetModelScale", "ctrlTextSecondary", "ctrlTextSelection", "curatorCameraArea", "currentVisionMode",
  "currentWeaponMode", "deleteMarkerLocal", "deleteVehicleCrew", "diag_captureFrame", "diag_exportConfig", "diag_lightNewLoad",
  "difficultyEnabled", "displayUniqueName", "doSuppressiveFire", "enableAutoTrimRTD", "enableEnvironment", "environmentVolume",
  "equipmentDisabled", "estimatedTimeLeft", "exportJIPMessages", "findEmptyPosition", "finishMissionInit", "forceGeneratorRTD",
  "forEachMemberTeam", "formationPosition", "gearSlotAmmoCount", "get3DENAttributes", "getDebriefingText", "getDLCAssetsUsage",
  "getHitPointDamage", "getLoadedModsInfo", "getMissionOptions", "getObjectArgument", "getObjectChildren", "getObjectTextures",
  "getPersonUsedDLCs", "getPosWorldVisual", "getPylonMagazines", "getSelectionBones", "getShadowDistance", "getUnloadInCombat",
  "getWaterLeakiness", "groupIconsVisible", "hcRemoveAllGroups", "HUDMovementLevels", "ignore3DENHistory", "is3DENMultiplayer",
  "isEqualTypeParams", "isFormationLeader", "isMultiplayerSolo", "isSwitchingWeapon", "isTutHintsEnabled", "lbSetPictureColor",
  "lbSetPictureRight", "leaderboardDeInit", "lightAttachObject", "lightDetachObject", "listRemoteTargets", "magazinesAmmoFull",
  "mapCenterOnCamera", "missionConfigFile", "missionDifficulty", "missionNameSource", "modelToWorldWorld", "nextMenuItemIndex",
  "nextWeatherChange", "onPlayerConnected", "onPreloadFinished", "playerRespawnTime", "ppEffectCommitted", "queryMagazinePool",
  "removeDiaryRecord", "removeHandgunItem", "removeWeaponCargo", "ropeAttachEnabled", "save3DENInventory", "selectionPosition",
  "sendSimpleCommand", "set3DENAttributes", "set3DENObjectType", "setCameraInterest", "setCamShakeParams", "setCollisionLight",
  "setCurrentChannel", "setDebriefingText", "setHitPointDamage", "setLightFlareSize", "setLightIntensity", "setMarkerDirLocal",
  "setMarkerPolyline", "setMarkerPosLocal", "setMissionOptions", "setObjectMaterial", "setParticleCircle", "setParticleParams",
  "setParticleRandom", "setPylonsPriority", "setShadowDistance", "setSimpleTaskType", "setTimeMultiplier", "setTrafficDensity",
  "setTriggerTimeout", "setUnitCombatMode", "setUnloadInCombat", "setUserActionText", "setVectorDirAndUp", "setVehicleAmmoDef",
  "setVehicleVarName", "setWaterLeakiness", "setWaypointScript", "simulationEnabled", "simulCloudDensity", "sliderSetPosition",
  "taskAlwaysVisible", "teamSwitchEnabled", "triggerActivation", "triggerStatements", "tvSetPictureColor", "tvSetPictureRight",
  "unlockAchievement", "userInputDisabled", "vectorDistanceSqr", "visibleScoretable", "waypointBehaviour", "waypointFormation",
  "weaponAccessories", "weaponsItemsCargo", "actionKeysImages", "addBackpackCargo", "addBinocularItem", "addCuratorAddons",
  "addCuratorPoints", "addItemToUniform", "addMagazineCargo", "airplaneThrottle", "allDiarySubjects", "allSimpleObjects",
  "assignedVehicles", "backpackSpaceFor", "camPrepareRelPos", "camPrepareTarget", "canAddItemToVest", "clearWeaponCargo",
  "configProperties", "create3DENEntity", "createGearDialog", "createSimpleTask", "ctFindHeaderRows", "ctHeaderControls",
  "ctrlAnimateModel", "ctrlMapAnimClear", "ctrlMapMouseOver", "ctrlScrollValues", "ctrlSetPositionH", "ctrlSetPositionW",
  "ctrlSetPositionX", "ctrlSetPositionY", "ctrlSetTextColor", "ctSetRowTemplate", "curatorMouseOver", "currentNamespace",
  "currentThrowable", "decayGraphValues", "deleteCollection", "diag_resetShapes", "diag_setLightNew", "difficultyOption",
  "disableUserInput", "elevatePeriscope", "enableDiagLegend", "enableRopeAttach", "enableSimulation", "enableTeamSwitch",
  "endLoadingScreen", "enginesTorqueRTD", "execEditorScript", "findEditorObject", "findNearestEnemy", "forceFlagTexture",
  "formationMembers", "gearIDCAmmoCount", "get3DENAttribute", "get3DENMouseOver", "getAllOwnedMines", "getAllPylonsInfo",
  "getAllUnitTraits", "getAnimSpeedCoef", "getArtilleryAmmo", "getBackpackCargo", "getCruiseControl", "getCustomAimCoef",
  "getMagazineCargo", "getMissionConfig", "getMissionLayers", "getMousePosition", "getOrDefaultCall", "getPlayerChannel",
  "getRotorBrakeRTD", "getSensorTargets", "getSensorThreats", "getTerrainHeight", "getTrimOffsetRTD", "getUnitMovesInfo",
  "getVehicleTIPars", "hideObjectGlobal", "isCopilotEnabled", "isEqualTypeArray", "isRemoteExecuted", "isShowing3DIcons",
  "isStaminaEnabled", "isTouchingGround", "isUAVConnectable", "isUniformAllowed", "isVehicleRadarOn", "isWeaponDeployed",
  "lbSetSelectColor", "leaderboardState", "linearConversion", "lnbSetColorRight", "lnbSetColumnsPos", "load3DENScenario",
  "locationPosition", "menuShortcutText", "missileTargetPos", "missionNamespace", "nearestLocations", "nearObjectsReady",
  "onGroupIconClick", "onMapSingleClick", "onPreloadStarted", "openYoutubeVideo", "overcastForecast", "parseSimpleArray",
  "parsingNamespace", "particlesQuality", "playerTargetLock", "posScreenToWorld", "posWorldToScreen", "processDiaryLink",
  "profileNamespace", "profileNameSteam", "progressPosition", "radioChannelInfo", "remoteControlled", "removeAllActions",
  "removeAllWeapons", "removeSimpleTask", "removeTeamMember", "roadsConnectedTo", "selectBestPlaces", "sentencesEnabled",
  "set3DENAttribute", "set3DENLogicType", "setAnimSpeedCoef", "setCruiseControl", "setCustomAimCoef", "setDefaultCamera",
  "setFaceAnimation", "setFormationTask", "setGroupIdGlobal", "setLightConePars", "setLightDayLight", "setLightUseFlare",
  "setMissileTarget", "setMousePosition", "setObjectTexture", "setParticleClass", "setRotorBrakeRTD", "setStaminaScheme",
  "setSystemOfUnits", "setTerrainHeight", "setVehicleTIPars", "setWaypointSpeed", "setWeaponZeroing", "showCinemaBorder",
  "simulSetHumidity", "simulWeatherSync", "soldierMagazines", "targetsAggregate", "taskMarkerOffset", "terrainIntersect",
  "triggerActivated", "tvSetSelectColor", "tvSortByValueAll", "uniformContainer", "uniformMagazines", "unitsBelowHeight",
  "updateObjectTree", "vectorDotProduct", "vectorNormalized", "vectorSideVisual", "waypointPosition", "actionKeysNames",
  "activatedAddons", "addEditorObject", "addEventHandler", "addMagazinePool", "addPlayerScores", "addWeaponGlobal",
  "addWeaponTurret", "all3DENEntities", "allDiaryRecords", "angularVelocity", "assignedVehicle", "assignToAirport",
  "attachedObjects", "boundingBoxReal", "buttonSetAction", "camPrepareFocus", "canDeployWeapon", "canVehicleCargo",
  "checkVisibility", "clearGroupIcons", "clearWeaponPool", "combatBehaviour", "compatibleItems", "configHierarchy",
  "configSourceMod", "connectToServer", "copyToClipboard", "createDiaryLink", "ctFindRowHeader", "ctRemoveHeaders",
  "ctrlMapAnimDone", "ctrlMapPosition", "ctrlSetPosition", "curatorSelected", "currentMagazine", "currentWaypoint",
  "deleteResources", "diag_resetAnims", "diag_stacktrace", "doArtilleryFire", "enableAIFeature", "enableEndDialog",
  "enableGunLights", "enableSentences", "enginesPowerRTD", "fadeEnvironment", "forceAddUniform", "forceFollowRoad",
  "forceWeaponFire", "forEachReversed", "formationLeader", "get3DENEntityID", "get3DENSelected", "getArtilleryETA",
  "getAssetDLCInfo", "getAttackTarget", "getBurningValue", "getCenterOfMass", "getConnectedUAV", "getDLCUsageTime",
  "getEditorCamera", "getPlayerScores", "getPosASLVisual", "getPosATLVisual", "getSlotItemName", "getTIParameters",
  "getTurretLimits", "getUserMFDValue", "getVehicleCargo", "getVideoOptions", "groupSelectUnit", "handgunMagazine",
  "importAllGroups", "initAmbientLife", "inputController", "isAbleToBreathe", "isAutoTrimOnRTD", "isDamageAllowed",
  "isSprintAllowed", "lbSetColorRight", "leaderboardInit", "lnbDeleteColumn", "lnbPictureRight", "lnbSetCurSelRow",
  "lnbSetTextRight", "lockedInventory", "magazinesDetail", "magazinesTurret", "mapGridPosition", "matrixTranspose",
  "menuSetShortcut", "moveInCommander", "moveObjectToEnd", "moveToCompleted", "namedProperties", "nearestBuilding",
  "nearestLocation", "objectFromNetId", "onBriefingGroup", "onBriefingNotes", "onShowNewObject", "ppEffectDestroy",
  "ppEffectEnabled", "preloadTitleObj", "preloadTitleRsc", "queryWeaponPool", "radioChannelAdd", "registeredTasks",
  "remove3DENLayer", "removeDrawLinks", "removeGroupIcon", "removeMagazines", "removeOwnedMine", "requiredVersion",
  "roleDescription", "ropeEndPosition", "ropesAttachedTo", "rotorsForcesRTD", "secondaryWeapon", "selectThrowable",
  "serverNamespace", "set3DENSelected", "setArmoryPoints", "setCenterOfMass", "setDropInterval", "setEngineRpmRTD",
  "setLightAmbient", "setMarkerShadow", "setParticleFire", "setPylonLoadout", "setTrafficSpeed", "setTurretLimits",
  "setUserMFDValue", "setVehicleArmor", "setVehicleCargo", "setVehicleRadar", "setViewDistance", "setWantedRPMRTD",
  "setWaypointName", "setWaypointType", "shownScoretable", "sideAmbientLife", "switchableUnits", "targetKnowledge",
  "taskDescription", "taskDestination", "triggerInterval", "unassignCurator", "unassignVehicle", "uniqueUnitItems",
  "unitAimPosition", "vectorDirVisual", "vectorMagnitude", "vehicleMoveInfo", "verifySignature", "visiblePosition",
  "waypointTimeout", "waypointVisible", "weaponDirection", "activateAddons", "addHandgunItem", "addWeaponCargo",
  "allowedService", "animationNames", "animationPhase", "animationState", "apertureParams", "arrayIntersect",
  "assignAsDriver", "assignAsGunner", "assignAsTurret", "assignedDriver", "assignedGunner", "assignedTarget",
  "attachedObject", "binocularItems", "boundingCenter", "brakesDisabled", "cameraInterest", "camPrepareBank",
  "camPrepareDive", "camSetFovRange", "channelEnabled", "checkAIFeature", "clearForcesRTD", "clearItemCargo",
  "commandingMenu", "createLocation", "ctrlFontHeight", "ctrlHTMLLoaded", "ctrlMapAnimAdd", "ctrlModelScale",
  "ctrlSetChecked", "ctrlSetFontH1B", "ctrlSetFontH2B", "ctrlSetFontH3B", "ctrlSetFontH4B", "ctrlSetFontH5B",
  "ctrlSetFontH6B", "ctrlSetTooltip", "ctrlTextHeight", "currentChannel", "currentCommand", "currentZeroing",
  "debriefingText", "deleteIdentity", "deleteLocation", "deleteWaypoint", "diag_deltaTime", "diag_localized",
  "emptyPositions", "enableCamShake", "enableCaustics", "enableIRLasers", "enginesIsOnRTD", "everyContainer",
  "flyInHeightASL", "getClientState", "getDescription", "getForcedSpeed", "getFSMVariable", "getGraphValues",
  "getMarkerColor", "getMissionDLCs", "getMissionPath", "getObjectProxy", "getObjectScale", "getPlateNumber",
  "getRepairCargo", "getShotParents", "getSuppression", "getTerrainGrid", "getTerrainInfo", "getTextureInfo",
  "getUnitLoadout", "getUserMFDText", "getWeaponCargo", "groupFromNetId", "hasPilotCamera", "insideBuilding",
  "isDLCAvailable", "isEqualTypeAll", "isEqualTypeAny", "isFlashlightOn", "isObjectHidden", "isSimpleObject",
  "isSteamMission", "isUAVConnected", "isVehicleCargo", "isWeaponRested", "lbPictureRight", "lbSetTextRight",
  "libraryCredits", "lineIntersects", "lnbSortByValue", "localNamespace", "lockedCameraTo", "markerPolyline",
  "matrixMultiply", "menuSetPicture", "mineDetectedBy", "missionVersion", "move3DENCamera", "nearestObjects",
  "objectCurators", "onBriefingPlan", "pickWeaponPool", "ppEffectAdjust", "ppEffectCommit", "ppEffectCreate",
  "ppEffectEnable", "preprocessFile", "productVersion", "publicVariable", "pushBackUnique", "queryItemsPool",
  "remoteExecCall", "removeAllItems", "removeBackpack", "removeDrawIcon", "removeHeadgear", "removeMagazine",
  "removeMenuItem", "respawnVehicle", "reversedMouseY", "ropeAttachedTo", "selectionNames", "selectNoPlayer",
  "sendTaskResult", "sendUDPMessage", "setAirportSide", "setAmmoOnPylon", "setApertureNew", "setCuratorCoef",
  "setCurrentTask", "setDestination", "setDriveOnPath", "setFeatureType", "setFlagTexture", "setFSMVariable",
  "setMarkerAlpha", "setMarkerBrush", "setMarkerColor", "setMarkerShape", "setMusicEffect", "setObjectProxy",
  "setObjectScale", "setPlateNumber", "setRectangular", "setRepairCargo", "setShotParents", "setSoundEffect",
  "setSuppression", "setTerrainGrid", "setTIParameter", "setTitleEffect", "setTriggerArea", "setTriggerText",
  "setTriggerType", "setUnconscious", "setUnitAbility", "setUnitLoadout", "setUnitPosWeak", "setUserMFDText",
  "setVehicleAmmo", "setVehicleLock", "shownSubtitles", "showScoretable", "sliderPosition", "sliderSetRange",
  "sliderSetSpeed", "surfaceIsWater", "surfaceTexture", "taskCustomData", "timeMultiplier", "triggerTimeout",
  "tvPictureRight", "unitCombatMode", "unregisterTask", "updateDrawIcon", "updateMenuItem", "vectorDistance",
  "vectorMultiply", "vectorUpVisual", "vehicleVarName", "visibleCompass", "waypointScript", "wingsForcesRTD",
  "addItemToVest", "addTeamMember", "addWeaponItem", "addWeaponPool", "aimedAtTarget", "airDensityRTD",
  "AISFinishHeal", "allAddonsInfo", "allExtensions", "allMapMarkers", "animateSource", "assignAsCargo",
  "assignCurator", "assignedCargo", "assignedGroup", "assignedItems", "attackEnabled", "backpackCargo",
  "backpackItems", "calculatePath", "callExtension", "camPrepareDir", "camPrepareFov", "camPreparePos",
  "cheatsEnabled", "clearItemPool", "collectiveRTD", "commandFollow", "commandGetOut", "commandTarget",
  "commitOverlay", "compileScript", "configClasses", "copyWaypoints", "countFriendly", "createDisplay",
  "createHashMap", "createTrigger", "createVehicle", "ctHeaderCount", "ctrlClassName", "ctrlCommitted",
  "ctrlMapCursor", "ctrlSetFontH1", "ctrlSetFontH2", "ctrlSetFontH3", "ctrlSetFontH4", "ctrlSetFontH5",
  "ctrlSetFontH6", "ctrlSetFontPB", "ctrlSetShadow", "ctrlTextColor", "ctrlTextWidth", "ctRowControls",
  "curatorAddons", "curatorCamera", "curatorPoints", "currentMuzzle", "currentWeapon", "deActivateKey",
  "deleteVehicle", "detectedMines", "diag_drawMode", "diag_tickTime", "disableBrakes", "displayParent",
  "displayUpdate", "drawRectangle", "enableChannel", "enableCopilot", "enableFatigue", "enableStamina",
  "enableTraffic", "enginesRpmRTD", "everyBackpack", "firstBackpack", "forEachMember", "formationTask",
  "freeExtension", "get3DENCamera", "get3DENEntity", "get3DENParent", "getAimingCoef", "getCargoIndex",
  "getDiverState", "getEditorMode", "getEntityInfo", "getGroupIcons", "getLightingAt", "getMarkerSize",
  "getMarkerType", "getObjectType", "getOpticsMode", "getResolution", "getServerInfo", "getWeaponSway",
  "handgunWeapon", "hasCustomFace", "hcGroupParams", "hcRemoveGroup", "hcSelectGroup", "hideSelection",
  "is3DENPreview", "isAutoHoverOn", "isGameFocused", "isMultiplayer", "isNotEqualRef", "kbAddDatabase",
  "kbRemoveTopic", "lbSetSelected", "lbSortByValue", "lnbColorRight", "lnbSetPicture", "lnbSetTooltip",
  "lockInventory", "magazineCargo", "magazinesAmmo", "mapAnimCommit", "markerChannel", "menuSetAction",
  "missileTarget", "moonIntensity", "nearestObject", "onDoubleClick", "pixelGridBase", "playableUnits",
  "playActionNow", "playersNumber", "preloadCamera", "preloadObject", "primaryWeapon", "putWeaponPool",
  "reloadEnabled", "remoteControl", "removeGoggles", "removeUniform", "resetCamShake", "runInitScript",
  "saveJoysticks", "savingEnabled", "screenToWorld", "sendAUMessage", "serverCommand", "setAttributes",
  "setAutonomous", "setCombatMode", "setEditorMode", "setFromEditor", "setGroupOwner", "setHideBehind",
  "setImportance", "setLightColor", "setLightnings", "setMarkerSize", "setMarkerText", "setMarkerType",
  "setOpticsMode", "setPilotLight", "setTaskResult", "setTrafficGap", "showSubtitles", "showWaypoints",
  "simulInClouds", "stopEngineRTD", "surfaceNormal", "switchGesture", "systemOfUnits", "systemTimeUTC",
  "taskCompleted", "textLogFormat", "tvCollapseAll", "tvSetSelected", "tvSortByValue", "vestContainer",
  "vestMagazines", "waypointSpeed", "weaponInertia", "weaponLowered", "weaponsTurret", "worldToScreen",
  "actionKeysEx", "actionParams", "add3DENLayer", "addGroupIcon", "addItemCargo", "addLiveStats",
  "addMagazines", "addOwnedMine", "addResources", "addScoreSide", "allCutLayers", "allowDammage",
  "allowFleeing", "allowService", "allVariables", "animatePylon", "armoryPoints", "assignedTeam",
  "attachObject", "briefingName", "buildingExit", "buttonAction", "camCommitted", "cameraEffect",
  "camPreloaded", "camSetRelPos", "camSetTarget", "canSlingLoad", "cbSetChecked", "clearOverlay",
  "closeDisplay", "closeOverlay", "commandRadio", "commandWatch", "compileFinal", "completedFSM",
  "countUnknown", "createCenter", "createDialog", "createMarker", "createTarget", "ctRemoveRows",
  "ctrlActivate", "ctrlMapScale", "ctrlPosition", "ctrlSetAngle", "ctrlSetFocus", "ctrlSetFontP",
  "ctrlSetModel", "ctrlSetScale", "currentPilot", "currentTasks", "cursorObject", "cursorTarget",
  "dateToNumber", "deleteCenter", "deleteMarker", "deleteStatus", "deleteTarget", "diag_enabled",
  "diag_frameNo", "displayChild", "dissolveTeam", "do3DENAction", "drawLocation", "drawTriangle",
  "drawXPolygon", "enableAttack", "enableMimics", "enableReload", "enableSaving", "eyeDirection",
  "fireAtTarget", "forceRespawn", "forceUnicode", "forgetTarget", "gearSlotData", "gestureState",
  "get3DENLayer", "getAmmoCargo", "getBoneNames", "getDirVisual", "getFuelCargo", "getGroupIcon",
  "getItemCargo", "getMarkerPos", "getModelInfo", "getObjectDLC", "getObjectFOV", "getOrDefault",
  "getPlayerUID", "getPosVisual", "getSlingLoad", "getStatValue", "getTextWidth", "getTowParent",
  "getUnitState", "getUnitTrait", "handgunItems", "hasInterface", "ignoreTarget", "inheritsFrom",
  "isAutonomous", "isForcedWalk", "isGamePaused", "isManualFire", "isNotEqualTo", "isPiPEnabled",
  "joinAsSilent", "lbColorRight", "lbIsSelected", "lbSetPicture", "lbSetTooltip", "leaveVehicle",
  "lnbAddColumn", "lnbCurSelRow", "lnbDeleteRow", "lnbTextRight", "loadBackpack", "loadIdentity",
  "loadMagazine", "lockCameraTo", "lockedDriver", "lockedTurret", "lockIdentity", "mapAnimClear",
  "markerShadow", "menuCollapse", "menuSetCheck", "menuSetValue", "menuShortcut", "missileState",
  "missionStart", "modelToWorld", "moveInDriver", "moveInGunner", "moveInTurret", "moveToFailed",
  "nearEntities", "nearestMines", "nearSupplies", "numberToDate", "objectParent", "onTeamSwitch",
  "openSteamApp", "preloadSound", "radioEnabled", "regexReplace", "registerTask", "removeAction",
  "removeWeapon", "ropeAttachTo", "ropeSegments", "rotorsRpmRTD", "safeZoneWAbs", "safeZoneXAbs",
  "saveIdentity", "selectLeader", "selectPlayer", "selectRandom", "selectWeapon", "set3DENLayer",
  "setAmmoCargo", "setBehaviour", "setBrakesRTD", "setDirection", "setFlagOwner", "setFormation",
  "setFuelCargo", "setGroupIcon", "setInfoPanel", "setMarkerDir", "setMarkerPos", "setNameSound",
  "setPiPEffect", "setRandomLip", "setSlingLoad", "setSpeedMode", "setStatValue", "setTargetAge",
  "setTaskState", "setTowParent", "setUnitTrait", "setVectorDir", "setVehicleId", "setWindForce",
  "shownCompass", "shownUAVFeed", "shownWarrant", "showWaypoint", "speechVolume", "switchAction",
  "switchCamera", "targetsQuery", "taskChildren", "titleFadeOut", "tvIsSelected", "tvSetPicture",
  "tvSetTooltip", "unassignItem", "unassignTeam", "uniformItems", "unitBackpack", "vectorFromTo",
  "vehicleRadio", "viewDistance", "visibleWatch", "waterDamaged", "waypointName", "waypointShow",
  "waypointType", "weaponsItems", "worldToModel", "a_greater_b", "activateKey", "addBackpack",
  "addCamShake", "addHeadgear", "addItemPool", "addMagazine", "addMenuItem", "addWaypoint",
  "airportSide", "allAirports", "allControls", "allCurators", "allDisplays", "allow3DMode",
  "allowDamage", "allowSprint", "allUnitsUAV", "ammoOnPylon", "animateDoor", "boundingBox",
  "buildingPos", "camSetFocus", "clientOwner", "closeDialog", "commandChat", "commandFire",
  "commandMove", "commandStop", "composeText", "createAgent", "createGroup", "ctAddHeader",
  "ctrlChecked", "ctrlEnabled", "ctrlSetFade", "ctrlSetFont", "ctrlSetText", "ctrlTooltip",
  "ctrlVisible", "ctSetCurSel", "curatorCoef", "currentTask", "customRadio", "deleteGroup",
  "deleteRange", "diag_enable", "diag_fpsMin", "diag_toggle", "didJIPOwner", "displayCtrl",
  "distanceSqr", "drawEllipse", "drawPolygon", "enableRadio", "failMission", "findDisplay",
  "flagTexture", "flyInHeight", "focusedCtrl", "fogForecast", "get3DENGrid", "getHideFrom",
  "getHitIndex", "getLighting", "getObjectID", "getPlayerID", "getPosWorld", "getRoadInfo",
  "getShotInfo", "getUserInfo", "getVariable", "globalRadio", "hcAllGroups", "hostMission",
  "inAreaArray", "inputAction", "isDedicated", "isEqualType", "isFlatEmpty", "isIRLaserOn",
  "isKeyActive", "isLocalized", "isObjectRTD", "isThrowable", "isTurnedOut", "isUIContext",
  "laserTarget", "lbSelection", "lbSetCurSel", "lbTextRight", "listObjects", "lnbAddArray",
  "lnbSetColor", "lnbSetValue", "loadOverlay", "loadUniform", "lockedCargo", "logEntities",
  "mapAnimDone", "markerAlpha", "markerBrush", "markerColor", "markerShape", "menuChecked",
  "menuEnabled", "menuPicture", "menuSetData", "menuSetText", "missionName", "moveInCargo",
  "musicVolume", "nearObjects", "nearTargets", "needService", "onEachFrame", "openDLCPage",
  "parseNumber", "playGesture", "playMission", "playMoveNow", "playSound3D", "playSoundUI",
  "profileName", "radioVolume", "rectangular", "removeItems", "ropeDestroy", "ropeUnwound",
  "saveOverlay", "set3DENGrid", "setAperture", "setCamUseTI", "setDrawIcon", "setFlagSide",
  "setHitIndex", "setHumidity", "setIdentity", "setOvercast", "setPlayable", "setPosition",
  "setPosWorld", "setRadioMsg", "setUnitRank", "setVariable", "setVectorUp", "setVelocity",
  "show3DIcons", "showCompass", "showUAVFeed", "showWarrant", "simpleTasks", "sliderRange",
  "sliderSpeed", "soundParams", "soundVolume", "splitString", "squadParams", "supportInfo",
  "suppressFor", "surfaceType", "swimInDepth", "switchLight", "toLowerANSI", "toUpperANSI",
  "triggerAmmo", "triggerArea", "triggerText", "triggerType", "turretLocal", "turretOwner",
  "tvExpandAll", "tvSelection", "tvSetCurSel", "uiNamespace", "vehicleChat", "weaponCargo",
  "weaponsInfo", "weaponState", "actionKeys", "actionName", "addGoggles", "addonFiles",
  "addUniform", "addVehicle", "allCameras", "allDeadMen", "allObjects", "allowGetIn",
  "allPlayers", "allTurrets", "animateBay", "assignItem", "assignTeam", "attachedTo",
  "camCommand", "camDestroy", "cameraView", "camPreload", "camSetBank", "camSetDive",
  "canSuspend", "captiveNum", "clearRadio", "combatMode", "commandFSM", "configFile",
  "configName", "countEnemy", "createMenu", "createMine", "createSite", "createTask",
  "createTeam", "createUnit", "ctrlCommit", "ctrlCreate", "ctrlDelete", "ctrlEnable",
  "ctrlMapDir", "ctrlParent", "ctrlSetURL", "ctrlShadow", "ctRowCount", "ctSetValue",
  "customChat", "cutFadeOut", "deleteSite", "deleteTeam", "diag_scope", "difficulty",
  "distance2D", "drawIcon3D", "drawLine3D", "editObject", "endMission", "fadeSpeech",
  "fileExists", "forceSpeed", "formatText", "formLeader", "fromEditor", "getDammage",
  "getFatigue", "getLeaning", "getPosASLW", "getStamina", "getTextRaw", "globalChat",
  "groupOwner", "groupRadio", "hcSelected", "hcSetGroup", "hcShownBar", "hideObject",
  "hintSilent", "importance", "infoPanels", "inputMouse", "isAutotest", "isBleeding",
  "isEngineOn", "isEqualRef", "isRealTime", "joinSilent", "joinString", "kbAddTopic",
  "kbHasTopic", "knowsAbout", "landResult", "lbSetColor", "lbSetValue", "lightnings",
  "limitSpeed", "lnbPicture", "lnbSetData", "lnbSetText", "loadConfig", "loadStatus",
  "lockDriver", "lockTurret", "logNetwork", "mapAnimAdd", "markerSize", "markerText",
  "markerType", "menuAction", "menuDelete", "menuEnable", "menuExpand", "menuSetURL",
  "mineActive", "missionEnd", "moveTarget", "needReload", "netObjNull", "newOverlay",
  "nMenuItems", "orderGetIn", "playAction", "playerSide", "rainParams", "regexMatch",
  "remoteExec", "removeItem", "removeVest", "revealMine", "ropeCreate", "ropeDetach",
  "ropeLength", "ropeUnwind", "saveStatus", "screenshot", "scriptDone", "scriptName",
  "serverName", "serverTime", "setAccTime", "setCaptive", "setDammage", "setFatigue",
  "setFormDir", "setGroupId", "setLightIR", "setMaxLoad", "setPosASL2", "setPosASLW",
  "setRainbow", "setSpeaker", "setStamina", "setUnitPos", "setWindDir", "setWindStr",
  "showLegend", "shownRadio", "shownWatch", "skillFinal", "switchMove", "systemChat",
  "systemTime", "taskParent", "taskResult", "teamMember", "teamSwitch", "throwables",
  "turretUnit", "tvCollapse", "tvSetColor", "tvSetValue", "UAVControl", "underwater",
  "unitAddons", "unitTurret", "unlinkItem", "vectorDiff", "vectorSide", "visibleGPS",
  "visibleMap", "WFSideText", "actionIDs", "actionNow", "addAction", "addRating",
  "addTorque", "addWeapon", "allGroups", "backpacks", "behaviour", "benchmark",
  "binocular", "cadetMode", "camCommit", "camCreate", "camSetDir", "camSetFov",
  "camSetPos", "camTarget", "camUseNVG", "cbChecked", "className", "commander",
  "countSide", "countType", "ctrlAngle", "ctrlModel", "ctrlScale", "ctrlShown",
  "ctrlStyle", "ctSetData", "diag_list", "direction", "directSay", "disableAI",
  "doorPhase", "drawArrow", "drawLaser", "fadeMusic", "fadeRadio", "fadeSound",
  "findCover", "flagOwner", "fogParams", "forcedMap", "forceWalk", "formation",
  "getCorpse", "getFriend", "getNumber", "getPosASL", "getPosATL", "getRelDir",
  "getRelPos", "groupChat", "hashValue", "hasWeapon", "hcShowBar", "hintCadet",
  "infoPanel", "inPolygon", "intersect", "isBurning", "isEqualTo", "isLaserOn",
  "isLightOn", "isWalking", "itemCargo", "kbWasSaid", "lbPicture", "lbSetData",
  "lbSetText", "lbTooltip", "lifeState", "lightIsOn", "lineBreak", "lnbAddRow",
  "lnbSortBy", "lockCargo", "lookAtPos", "magazines", "markerDir", "markerPos",
  "menuClear", "menuHover", "menuValue", "modParams", "moonPhase", "moveInAny",
  "nameSound", "nearRoads", "objStatus", "parseText", "pixelGrid", "playMusic",
  "playSound", "precision", "regexFind", "resources", "safeZoneH", "safeZoneW",
  "safeZoneX", "safeZoneY", "scoreSide", "scudState", "selectMax", "selectMin",
  "setDamage", "setFriend", "setLeader", "setPosASL", "setPosATL", "setSpeech",
  "shownChat", "showRadio", "showWatch", "sideRadio", "speedMode", "stopSound",
  "sunOrMoon", "taskState", "terminate", "titleText", "tvPicture", "tvSetData",
  "tvSetText", "tvSortAll", "tvTooltip", "unitIsUAV", "unitReady", "vectorAdd",
  "vectorCos", "vectorDir", "vestItems", "waypoints", "weightRTD", "worldName",
  "worldSize", "a_hash_b", "a_less_b", "addForce", "addScore", "AGLToASL",
  "allMines", "allSites", "allUnits", "allUsers", "ASLToAGL", "ASLToATL",
  "ATLToASL", "attachTo", "backpack", "cameraOn", "canStand", "configOf",
  "ctAddRow", "ctCurSel", "ctrlFade", "ctrlShow", "ctrlText", "ctrlType",
  "debugFSM", "debugLog", "deleteAt", "diag_fps", "diag_log", "distance",
  "doFollow", "doGetOut", "doTarget", "drawIcon", "drawLine", "drawLink",
  "enableAI", "engineOn", "entities", "flagSide", "forceEnd", "forceMap",
  "freeLook", "fromJSON", "fullCrew", "getArray", "getSpeed", "getWPPos",
  "glanceAt", "handsHit", "hcLeader", "headgear", "hideBody", "htmlLoad",
  "humidity", "inflamed", "isHidden", "isKindOf", "isNumber", "isOnRoad",
  "isPlayer", "isSaving", "isServer", "keyImage", "language", "lbCurSel",
  "lbDelete", "lbSortBy", "linkItem", "lnbClear", "lnbColor", "lnbValue",
  "loadFile", "loadGame", "loadVest", "localize", "menuData", "menuSize",
  "menuSort", "menuText", "moveTime", "overcast", "playMove", "position",
  "priority", "pushBack", "saveGame", "sendTask", "setGusts", "setMimic",
  "setOwner", "setPitch", "setSkill", "setWaves", "setWPPos", "showChat",
  "shownGPS", "shownHUD", "shownMap", "shownPad", "sideChat", "skipTime",
  "someAmmo", "taskHint", "taskName", "taskType", "teamName", "teamType",
  "titleCut", "titleObj", "titleRsc", "toString", "tvCurSel", "tvDelete",
  "tvExpand", "typeName", "vectorUp", "vehicles", "velocity", "accTime",
  "addItem", "addMenu", "addVest", "allDead", "allLODs", "animate",
  "canFire", "canMove", "captive", "comment", "compile", "ctClear",
  "ctrlIDC", "ctrlIDD", "ctrlURL", "ctValue", "cutText", "dayTime",
  "doWatch", "execFSM", "faction", "findAny", "flatten", "fleeing",
  "focusOn", "getDLCs", "getMass", "getText", "goggles", "groupId",
  "inflame", "isAgent", "isArray", "isAwake", "isClass", "isFinal",
  "kbReact", "keyName", "lbClear", "lbColor", "lbValue", "lnbData",
  "lnbSize", "lnbSort", "lnbText", "loadAbs", "maxLoad", "members",
  "menuAdd", "menuURL", "moveOut", "openGPS", "openMap", "rainbow",
  "reverse", "ropeCut", "saveVar", "setAmmo", "setDate", "setFace",
  "setFuel", "setMass", "setName", "setRain", "setRank", "setSide",
  "setSize", "setText", "setType", "setWind", "showGPS", "showHUD",
  "showMap", "showPad", "speaker", "stopped", "targets", "textLog",
  "toArray", "toFixed", "toLower", "toUpper", "tvClear", "tvCount",
  "tvValue", "uiSleep", "uniform", "unitPos", "vehicle", "weapons",
  "windDir", "windRTD", "windStr", "a_or_b", "action", "agents",
  "aimPos", "append", "assert", "canAdd", "ctData", "ctrlAt",
  "cutObj", "cutRsc", "damage", "detach", "dialog", "didJIP",
  "doFire", "doMove", "doStop", "driver", "execVM", "eyePos",
  "findIf", "finite", "format", "getDir", "getHit", "getPos",
  "groups", "gunner", "import", "inArea", "insert", "is3DEN",
  "isNull", "isText", "joinAs", "kbTell", "landAt", "lbData",
  "lbSize", "lbSort", "lbText", "leader", "locked", "lockWP",
  "lookAt", "morale", "moveTo", "pixelH", "pixelW", "player",
  "random", "rankId", "rating", "reload", "resize", "reveal",
  "roadAt", "select", "setDir", "setFog", "setHit", "setPos",
  "sizeOf", "stance", "toJSON", "tvData", "tvSort", "tvText",
  "typeOf", "uiTime", "values", "admin", "agent", "alive",
  "apply", "atan2", "awake", "break", "count", "doFSM",
  "floor", "group", "gusts", "hintC", "image", "isNil",
  "items", "lbAdd", "local", "merge", "netId", "owner",
  "param", "pitch", "ropes", "round", "say2D", "say3D",
  "score", "skill", "sleep", "spawn", "speed", "teams",
  "tvAdd", "units", "waves", "acos", "ammo", "asin",
  "atan", "call", "ceil", "crew", "date", "drop",
  "echo", "endl", "exec", "exit", "face", "find",
  "fire", "flag", "fuel", "goto", "halt", "hint",
  "join", "keys", "land", "list", "load", "lock",
  "move", "name", "pose", "rain", "rank", "side",
  "size", "sort", "sqrt", "stop", "text", "time",
  "trim", "type", "vest", "wind", "abs", "atg",
  "cos", "deg", "exp", "fog", "get", "hmd",
  "log", "max", "min", "rad", "say", "set",
  "sin", "str", "tan", "in", "ln", "pi",
  "tg",
];

const SQF_KEYWORDS = [
  "continueWith", "privateAll", "breakWith", "scopeName", "waitUntil", "breakOut", "continue", "exitWith", "breakTo", "default", "forEach", "private", "params", "switch", "catch", "throw", "while", "case", "else", "from", "step", "then", "with", "for", "try", "do", "if", "to",
];

const SQF_CONSTANTS = [
  "diaryRecordNull", "teamMemberNull", "locationNull", "sideFriendly", "controlNull", "displayNull", "independent", "sideUnknown", "configNull", "resistance", "scriptNull", "sideEmpty", "sideEnemy", "sideLogic", "civilian", "taskNull", "grpNull", "objNull", "blufor", "false", "opfor", "east", "true", "west", "nil",
];

const SQF_MAGIC_VARS = [
  "_forEachIndex", "thisTrigger", "_exception", "thisScript", "thisArgs", "thisList", "_this", "this", "_x", "_y",
];

const SQF_WORD_OPERATORS = [
  "and", "mod", "not", "or",
];

// Preprocessor directives — https://community.bistudio.com/wiki/PreProcessor_Commands
const SQF_PREPROCESSOR_DIRECTIVES = [
  "include", "define", "undef", "ifdef", "ifndef", "if", "else", "endif",
];

// Predefined preprocessor macros
const SQF_PREPROCESSOR_MACROS = [
  "__LINE__", "__FILE__", "__FILE_NAME__", "__FILE_SHORT__", "__has_include",
  "__DATE_ARR__", "__DATE_STR__", "__DATE_STR_ISO8601__", "__TIME__", "__TIME_UTC__",
  "__DAY__", "__MONTH__", "__YEAR__", "__COUNTER__", "__TIMESTAMP_UTC__",
  "__COUNTER_RESET__", "__RAND_INT8__", "__RAND_INT16__", "__RAND_INT32__",
  "__RAND_INT64__", "__RAND_UINT8__", "__RAND_UINT16__", "__RAND_UINT32__",
  "__RAND_UINT64__", "__GAME_VER__", "__GAME_VER_MAJ__", "__GAME_VER_MIN__",
  "__GAME_BUILD__", "__A3_DIAG__", "__ARMA__", "__ARMA3__", "__A3_DEBUG__",
  "__A3_EXPERIMENTAL__", "__A3_PROFILING__", "__EXEC", "__EVAL",
];

const joinAlt = (items: readonly string[]): string => items.join("|");

const COMMANDS_ALT = joinAlt(SQF_COMMANDS);
const KEYWORDS_ALT = joinAlt(SQF_KEYWORDS);
const CONSTANTS_ALT = joinAlt(SQF_CONSTANTS);
const MAGIC_VARS_ALT = joinAlt(SQF_MAGIC_VARS);
const WORD_OPERATORS_ALT = joinAlt(SQF_WORD_OPERATORS);
const PREPROC_DIRECTIVES_ALT = joinAlt(SQF_PREPROCESSOR_DIRECTIVES);
const PREPROC_MACROS_ALT = SQF_PREPROCESSOR_MACROS.join("|");

export const sqfGrammar: LanguageRegistration = {
  name: "sqf",
  scopeName: "source.sqf",
  displayName: "SQF",
  aliases: [],
  patterns: [
    { include: "#comments" },
    { include: "#preprocessor" },
    { include: "#strings" },
    { include: "#numbers" },
    { include: "#constants" },
    { include: "#magic-variables" },
    { include: "#keywords" },
    { include: "#word-operators" },
    { include: "#commands" },
    { include: "#local-variable" },
    { include: "#constant-variable" },
    { include: "#global-variable" },
    { include: "#operators" },
    { include: "#punctuation" },
  ],
  repository: {
    comments: {
      patterns: [
        { match: "//.*$", name: "comment.line.double-slash.sqf" },
        {
          begin: "/\\*",
          end: "\\*/",
          name: "comment.block.sqf",
        },
      ],
    },
    preprocessor: {
      patterns: [
        {
          // Line-continuation backslash — visible at EOL
          match: "\\\\$",
          name: "constant.character.escape.line-continuation.sqf",
        },
        {
          // #include "file" | #include <file>
          begin: "^\\s*(#\\s*include)\\s*",
          beginCaptures: {
            "1": { name: "keyword.control.directive.include.sqf" },
          },
          end: "$",
          patterns: [
            {
              begin: '"',
              end: '"',
              name: "string.quoted.double.include.sqf",
            },
            {
              begin: "<",
              end: ">",
              name: "string.quoted.other.lt-gt.include.sqf",
            },
          ],
        },
        {
          match: "^\\s*(#\\s*(?:" + PREPROC_DIRECTIVES_ALT + "))\\b",
          captures: {
            "1": { name: "keyword.control.directive.sqf" },
          },
        },
        {
          // Stringify and paste operators used inside macros
          match: "##|#(?=[A-Za-z_])",
          name: "keyword.operator.preprocessor.sqf",
        },
        {
          match: "\\b(?:" + PREPROC_MACROS_ALT + ")\\b",
          name: "constant.language.preprocessor.sqf",
        },
      ],
    },
    strings: {
      patterns: [
        {
          name: "string.quoted.double.sqf",
          begin: '"',
          end: '"',
          patterns: [
            { match: '""', name: "constant.character.escape.sqf" },
          ],
        },
        {
          name: "string.quoted.single.sqf",
          begin: "'",
          end: "'",
          patterns: [
            { match: "''", name: "constant.character.escape.sqf" },
          ],
        },
      ],
    },
    numbers: {
      patterns: [
        {
          match: "\\b0[xX][0-9a-fA-F]+\\b",
          name: "constant.numeric.hex.sqf",
        },
        {
          match: "\\$[0-9a-fA-F]+\\b",
          name: "constant.numeric.hex.sqf",
        },
        {
          match: "\\b[0-9]+(?:\\.[0-9]+)?(?:[eE][+-]?[0-9]+)?\\b",
          name: "constant.numeric.sqf",
        },
        {
          match: "(?<![A-Za-z0-9_])\\.[0-9]+(?:[eE][+-]?[0-9]+)?\\b",
          name: "constant.numeric.sqf",
        },
      ],
    },
    constants: {
      patterns: [
        {
          match: "(?i)\\b(?:" + CONSTANTS_ALT + ")\\b",
          name: "constant.language.sqf",
        },
      ],
    },
    "magic-variables": {
      patterns: [
        {
          match: "(?i)(?<![A-Za-z0-9_])(?:" + MAGIC_VARS_ALT + ")\\b",
          name: "variable.language.this.sqf",
        },
      ],
    },
    keywords: {
      patterns: [
        {
          match: "(?i)\\b(?:" + KEYWORDS_ALT + ")\\b",
          name: "keyword.control.sqf",
        },
      ],
    },
    "word-operators": {
      patterns: [
        {
          match: "(?i)\\b(?:" + WORD_OPERATORS_ALT + "|greater=|less=|greater|less|hash)\\b",
          name: "keyword.operator.word.sqf",
        },
      ],
    },
    commands: {
      patterns: [
        {
          match: "(?i)\\b(?:" + COMMANDS_ALT + ")\\b",
          name: "support.function.sqf",
        },
      ],
    },
    "local-variable": {
      patterns: [
        {
          // Locals start with underscore — scoped to script/function/control block.
          match: "\\b_[A-Za-z0-9_]*\\b",
          name: "variable.parameter.local.sqf",
        },
      ],
    },
    "constant-variable": {
      patterns: [
        {
          // TAG_CONSTANT / SCREAMING_SNAKE globals — convention for read-only constants.
          match: "\\b[A-Z][A-Z0-9_]*(?:_[A-Z0-9]+)+\\b",
          name: "variable.other.constant.sqf",
        },
        {
          // Pure UPPER_CASE single token (3+ chars).
          match: "\\b[A-Z][A-Z0-9]{2,}\\b",
          name: "variable.other.constant.sqf",
        },
      ],
    },
    "global-variable": {
      patterns: [
        {
          // Any remaining identifier — globals live in missionNamespace.
          match: "\\b[A-Za-z][A-Za-z0-9_]*\\b",
          name: "entity.name.variable.global.sqf",
        },
      ],
    },
    operators: {
      patterns: [
        {
          // Config path operator
          match: ">>",
          name: "keyword.operator.config.sqf",
        },
        {
          // Select shorthand (Arma 3)
          match: "#",
          name: "keyword.operator.select.sqf",
        },
        {
          match: "&&|\\|\\||!=|==|<=|>=|<|>|!",
          name: "keyword.operator.comparison.sqf",
        },
        {
          match: "\\+=|-=|\\*=|/=|=",
          name: "keyword.operator.assignment.sqf",
        },
        {
          match: "\\+|-|\\*|/|%|\\^",
          name: "keyword.operator.arithmetic.sqf",
        },
      ],
    },
    punctuation: {
      patterns: [
        { match: ";", name: "punctuation.terminator.statement.sqf" },
        { match: ",", name: "punctuation.separator.sqf" },
        { match: "[\\[\\]]", name: "punctuation.section.array.sqf" },
        { match: "[{}]", name: "punctuation.section.block.sqf" },
        { match: "[()]", name: "punctuation.section.parens.sqf" },
      ],
    },
  },
};
